name: Matrix Tor Status

on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tor and curl
        run: sudo apt-get update && sudo apt-get install -y tor curl

      - name: Start Tor
        run: |
          tor --SocksPort 9050 --RunAsDaemon 1
          # Wait for Tor bootstrap
          for i in {1..30}; do
            sleep 1
            if grep -q "Bootstrapped 100%" /var/lib/tor/notice.log 2>/dev/null; then
              break
            fi
          done

      - name: Check .onion status
        env:
          MATRIX_ONION: ${{ secrets.MATRIX_ONION }}
        run: |
          mkdir -p public
          STATUS="DOWN"
          CODE=0
          URL="${MATRIX_ONION%/}/_matrix/client/versions"
          RESP=$(curl -sS --socks5-hostname 127.0.0.1:9050 --max-time 20 -w '%{http_code}' "$URL" || echo "000")
          if [ "$RESP" = "200" ]; then
            STATUS="UP"
            CODE=200
          fi
          jq -n --arg status "$STATUS" --argjson code "$CODE" '{status:$status, http_code:$code}' > public/status.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
